DataQualityCommittee/dqc_us_rules

- src/__init__.py
Added a logging plugin to the plugin init to allow for easier plugin integration for end users.
> Logging Plugin Update

- docs/DQC_US_0005/DQC_0005.md
- docs/DQC_US_0009/DQC_0009.md
> Form fixes

- dqc_us_rules/dqc_us_0004.py
Fixed an issue where infinite precision could cause exceptions to be raised
@hermfischer-wf
> Infinity Precision in DQC 4

- setup.py
This updates the required meta data to represent the custom license from XBRL US
> Updated meta data for Python Global Index.

- requirements_dev.txt
- tests/unit_tests/test_dqc_us_0004.py
- tests/unit_tests/test_dqc_us_0005.py
- tests/unit_tests/test_dqc_us_0006.py
- tests/unit_tests/test_dqc_us_0009.py
- tests/unit_tests/test_dqc_us_0015.py
- tests/unit_tests/test_dqc_us_0033_0036.py
- tests/unit_tests/test_init.py
- tests/unit_tests/util/test_facts.py
- Updated the unit tests to correct import paths and code style.
This PR is Dependent on https://github.com/DataQualityCommittee/dqc_us_rules/pull/56
> Cleanup and fixes for existent unit tests.

- docs/DQC_US_0015/DQC_0015.md
Add Appendix B to show approved changes to axis/member exclusions and to remove listed line items from Rule 0015 from initial post-implementation review.
> Add post-implementation review edits to Rule 0015

- dqc_us_rules/__init__.py
- dqc_us_rules/dqc_us_0004.py
- dqc_us_rules/dqc_us_0005.py
- dqc_us_rules/dqc_us_0006.py
- dqc_us_rules/dqc_us_0009.py
- dqc_us_rules/dqc_us_0015.py
- dqc_us_rules/dqc_us_0033_0036.py
- dqc_us_rules/util/facts.py
- dqc_us_rules/util/messages.py
- Line lengths of everything are now under 80 character
- Every function contains a summary of the function
- Every function contains a comment on the usage of each parameter
- Every function contains a comment on the type of each parameter
- Every function with a return value contains a comment on the type of the value returned
- Every function with a return value contains a summary of what is being returned
- All unnecessary imports removed
- All unused variables removed
- All parameters of functions are lowercase
> Make everything in DQC pass flake8 tests except for the Unit Tests

- dqc_us_rules/dqc_us_0004.py
- dqc_us_rules/dqc_us_0015.py
- requirements-dev.txt
- tests/__init__.py
- tests/unit_tests/__init__.py
- tests/unit_tests/test_dqc_us_0004.py
- tests/unit_tests/test_dqc_us_0005.py
- tests/unit_tests/test_dqc_us_0006.py
- tests/unit_tests/test_dqc_us_0009.py
- tests/unit_tests/test_dqc_us_0015.py
- tests/unit_tests/test_dqc_us_0033_0036.py
- tests/unit_tests/test_init.py
- tests/unit_tests/util/__init__.py
- tests/unit_tests/util/test_facts.py
- All line lengths are less than 80 characters
- All variable names are lowercase
- All unused variables removed
> Fix flake8 Errors in Unit Tests

- dqc_us_rules/__init__.py
- dqc_us_rules/dqc_us_0004.py
- dqc_us_rules/dqc_us_0005.py
- dqc_us_rules/dqc_us_0006.py
- dqc_us_rules/dqc_us_0009.py
- dqc_us_rules/dqc_us_0015.py
- dqc_us_rules/dqc_us_0033_0036.py
- dqc_us_rules/util/facts.py
- dqc_us_rules/util/messages.py
- requirements-dev.txt
- tests/__init__.py
- tests/unit_tests/__init__.py
- tests/unit_tests/test_dqc_us_0004.py
- tests/unit_tests/test_dqc_us_0005.py
- tests/unit_tests/test_dqc_us_0006.py
- tests/unit_tests/test_dqc_us_0009.py
- tests/unit_tests/test_dqc_us_0015.py
- tests/unit_tests/test_dqc_us_0033_0036.py
- tests/unit_tests/test_init.py
- tests/unit_tests/util/__init__.py
- tests/unit_tests/util/test_facts.py
- Updated with current master.
> XS-2913: Update Next Q1 2016 with current DQC Master

- dqc_us_rules/dqc_us_0033_0036.py
- tests/unit_tests/test_dqc_us_0033_0036.py
- Added function to check if a fact was valid
- Updated unit tests
> Fix error caused by ModelFact.xValue being None

- dqc_us_rules/dqc_us_0033_0036.py
- tests/unit_tests/test_dqc_us_0033_0036.py
- Change _doc_period_end_date_check to return the correct number of errors
- Update unit test to test correctly
> Fix wrong number of errors being returned by dqc_us_0033_0036.py

- MANIFEST.in
- Added all resource csv files to the manifest so that they are included in the distribution.
> Expand the MANIFEST.in to include all needed files for packaging.

- dqc_us_rules/_pkg_meta.py
Package meta update for release
> updated package meta to 1.0.8

- MANIFEST.in
- dqc_us_rules/_pkg_meta.py
- dqc_us_rules/dqc_us_0004.py
- dqc_us_rules/dqc_us_0033_0036.py
- tests/unit_tests/test_dqc_us_0033_0036.py
- Update next_q1_16 branch with current master of DQC.
> Update next_q1_16 with current DQC master.

- dqc_us_rules/dqc_us_0015.py
- tests/unit_tests/test_dqc_us_0015.py
- Changed function name
- updated tests
> Refactor contains_insensitive

- dqc_us_rules/dqc_us_0005.py
- tests/unit_tests/test_dqc_us_0005.py
- Extracted big check to function.
- Added tests.
> Extract if/elif checks from DQC 5

- dqc_us_rules/dqc_us_0018.py
- Create json caches on-demand, when not present.
- Removed unnecessary arelle logging in the rule.
> On-demand deprecated concept caching

- dqc_us_rules/dqc_us_0005.py
- dqc_us_rules/dqc_us_0018.py
- tests/unit_tests/test_dqc_us_0005.py
- Styleguide changes as suggested in https://github.com/DataQualityCommittee/dqc_us_rules/pull/84
- Based off of https://github.com/DataQualityCommittee/dqc_us_rules/pull/93
> DQC 18 styling.

- dqc_us_rules/_pkg_meta.py
Created to tag with a release candidate version
> RC 1 Release version update

- dqc_us_rules/__init__.py
- dqc_us_rules/dqc_us_0018.py
- dqc_us_rules/dqc_us_0041.py
- tests/unit_tests/test_dqc_us_0041.py
* Moved logic into _default_dimension_mismatch function.
* Update unit tests.
*Encapsulated the main plugin loop in a generic exception class to avoid unhandled bubbling up into Arelle.
Please review: @hefischer @andrewperkins-wf
> XS-3032: Defensive improvements

- dqc_us_rules/__init__.py
- dqc_us_rules/dqc_us_0013.py
- dqc_us_rules/dqc_us_0014.py
- dqc_us_rules/dqc_us_0041.py
- dqc_us_rules/util/facts.py
- tests/unit_tests/test_dqc_us_0013.py
- tests/unit_tests/test_dqc_us_0014.py
More issues with the new rules that we needed to get fixed.  Mostly around None checks and the like.
* None checks, value checks, and more!
> XS-3032: Logic for 0041 was flawed, corrected.

- dqc_us_rules/_pkg_meta.py
This is a version update for the 2.0.0.RC2 Release candidate.
> Release Candidate version update

- dqc_us_rules/_pkg_meta.py
made an RC3 since the RC2 was tagged wrong, and github does weird behavior with deleted tags.
> RC3 Release PR

- dqc_us_rules/resources/DQC_US_0001/dqc_0001.json
- Added new configs from spreadsheet here: https://github.com/DataQualityCommittee/dqc_us_rules/pull/110
> Add new configs for DQC1.

- dqc_us_rules/dqc_us_0005.py
- tests/unit_tests/test_dqc_us_0005.py
- Added an exception list and validation skipping to 0005.
- Added a new unit test to test the skipping mechanic.
> XS-3078: Exclude S-1 and S-11 reports from DQC_0005

- dqc_us_rules/resources/DQC_US_0014/dqc_14_concepts.csv
- Updated configs.
- No tests since it's a config change.
> Add configs for DQC 14

- dqc_us_rules/_pkg_meta.py
> RC4 Version Update

- dqc_us_rules/_pkg_meta.py
- Updated version to 2.0.0.RC5
> RC5 Update Version

- dqc_us_rules/dqc_us_0001.py
- dqc_us_rules/dqc_us_0006.py
- dqc_us_rules/util/facts.py
- tests/unit_tests/test_dqc_us_0001.py
- tests/unit_tests/test_dqc_us_0005.py
- tests/unit_tests/util/test_facts.py
Original review PR here:
https://github.com/DataQualityCommittee/dqc_us_rules/pull/123
> XS-3091 DQC Rule 1 Needs All Facts 

- dqc_us_rules/dqc_us_0041.py
-Changed index from .16 to .73 as specified by the rule
> Changed index from .16 to .73

- dqc_us_rules/dqc_us_0001.py
- tests/unit_tests/test_dqc_us_0001.py
- Updated the extensions part of DQC1 to work like the others.  Updated tests.
> Handle the extensions case for DQC 1

- dqc_us_rules/dqc_us_0033_0036.py
- tests/unit_tests/test_dqc_us_0033_0036.py
- Merged master into next_q1_16
> XS-3115: Master merge

- dqc_us_rules/dqc_us_0018.py
- dqc_us_rules/util/message_info.json
[XS-3109](https://jira.webfilings.com/browse/XS-3109) - DQC 18: needs to throw index .34
-
- Overwrote the old message with the new message in mapping-info.json
- Added the index code to DQC 18
- Filing doc to use for testing is attached to the Jira ticket
-
Please review: @jasonleinbach-wf @chrislococo-wf @andrewperkins-wf @brianmyers-wf @bradbenjamin-wf @derekgengenbacher-wf
> XS-3109 DQC 18: needs to throw index .34

- dqc_us_rules/_pkg_meta.py
- Updated version to 2.0.0.RC6
> Updated version to release candidate 6

- dqc_us_rules/_pkg_meta.py
- dqc_us_rules/util/message_info.json
> Fix typo in DQC 18.

- dqc_us_rules/util/message_info.json
- Fixed message on dqc 18 from element.name to fact1.name
> Fixed message

- dqc_us_rules/dqc_us_0033_0036.py
- tests/unit_tests/test_dqc_us_0033_0036.py
- Used for/else logic to handle dimensionless 36-33 interactions.
- Updated unit tests to reflect changes.
> XS-3123: Corrections to the 33/36 interactions.

- dqc_us_rules/dqc_us_0005.py
- tests/unit_tests/test_dqc_us_0005.py
[XS-3018](https://jira.webfilings.com/browse/XS-3018) - Handle SG followup from XS-2905
-
Fixed style guide issues that were discovered while testing XS-2905
-
Please review: @jasonleinbach-wf @chrislococo-wf @andrewperkins-wf @brianmyers-wf @bradbenjamin-wf @derekgengenbacher-wf
> XS-3018 Handle SG followup from XS-2905

- dqc_us_rules/dqc_us_0018.py
- dqc_us_rules/util/message_info.json
- tests/unit_tests/test_dqc_us_0018.py
- Changed rule 18 to check deprecated concepts of non-facts too
> Fix rule 18 to check non-fact concepts

- dqc_us_rules/dqc_us_0001.py
- tests/unit_tests/test_dqc_us_0001.py
- Add errorCount to errors with locators.
- Update tests.
> Add errorCount to DQC1

- dqc_us_rules/dqc_us_0033_0036.py
- tests/unit_tests/test_dqc_us_0033_0036.py
- 1.  Changed the code in dqc_us_0033_0036.py to handle the case where a 36 can fire with dimensions and a 33 without dimensions can still fire as well
- 2.  Added a unit test to test the case of dimensions and having both a 36 and 33 fire
> XS-3135 DQC 33/36 needs a complicated test case.

- dqc_us_rules/dqc_us_0001.py
- tests/unit_tests/test_dqc_us_0001.py
- Added a dict to track axis/members that were fired.
- Updated tests.
> Only fire once per axis/member pair.

- dqc_us_rules/_pkg_meta.py
- Updated the release version to 2.0.0RC9
> Update release version to RC9

- dqc_us_rules/_pkg_meta.py
> Updated version to 2.0.0rc10

- docs/DQC_US_0015/DQC_0015.md
Update MD for new spreadsheet names for list of elements and member exclusions - does not affect existing spreadsheet names, only MD documentation.
Please review @andrewperkins-wf @jasonleinbach-wf  @chrislococo-wf
> Update MD for new spreadsheet names 

- dqc_us_rules/_pkg_meta.py
- Updated version pin for RC11
> Update pin to 2.0.0RC11

- docs/DQC_US_0015/DQC_0015.md
- docs/README.md
- dqc_us_rules/util/__init__.py
- dqc_us_rules/util/facts.py
- dqc_us_rules/util/message_info.json
- dqc_us_rules/util/messages.py
@andrewperkins-wf as discussed today, these are .py files that should be updated. There's also a proposed docs readme with col for _rule_version and a residual edit from earlier comment on DQC_0015 documentation.
> Update for current year

- docs/README.md
- dqc_us_rules/dqc_us_0001.py
- dqc_us_rules/dqc_us_0013.py
- dqc_us_rules/dqc_us_0014.py
- dqc_us_rules/dqc_us_0015.py
- dqc_us_rules/dqc_us_0018.py
- dqc_us_rules/dqc_us_0033_0036.py
- dqc_us_rules/dqc_us_0041.py
- dqc_us_rules/util/facts.py
- tests/unit_tests/test_dqc_us_0013.py
* DQC 13 needed updates to its pre-requisite configurations
* Needed to update rules that were updated to version 2.0
* Fixed some flake 8 errors
* Updated the version numbers in the rule files
* Updated the DQC 13 precondition configurations
* Fixed some Flake 8 failures
* Test that DQC 13 is fixed
DQC 13, plus other rule definitions
None since this was a configuration change
> DQC Rule 13 Updates

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Added a `.github` folder with a PR template and placeholder for issue and contributing templates.
- Updated the README.md to document the software development lifecycle.
- Removed PR template from the README.md, as it will now auto-populate once this ticket merges.
- Added the QA Template in order to standardize the QA process for the library.
> XS-2873: Update the documentation for DQC

- dqc_us_rules/dqc_us_0013.py
- dqc_us_rules/dqc_us_0018.py
- Attr check on val.usgaapDeprecations
> Add attr checks for the cache.  Refs XS-3207

- dqc_us_rules/_pkg_meta.py
- Updated the release pin to 2.0.0.RC12
> Update pin to 2.0.0RC12

- dqc_us_rules/_pkg_meta.py
> Update pin to 2.0.0RC13

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Recreation of the original Pull request found [here](https://github.com/DataQualityCommittee/dqc_us_rules/pull/156)
> XS-2873: Document the SDLC

- dqc_us_rules/_pkg_meta.py
- dqc_us_rules/dqc_us_0005.py
- dqc_us_rules/dqc_us_0015.py
- dqc_us_rules/util/facts.py
- dqc_us_rules/util/neg_num.py
- tests/unit_tests/test_dqc_us_0005.py
- tests/unit_tests/test_dqc_us_0015.py
- patched dqc_us_0005.py to the latest in next_q1_16 for immediate release
- patched dqc_us_0015.py to the latest in next_q1_16 for immediate release
- updated version pin from 1.0.0 to 1.1.0 for release.
- patched the test files for 0015 and 0005.
- brought over the util/neg_num.py file as it is used by 0015.
> XS-3229: Update 0005 and 0015 from next_q1_16 to master

- dqc_us_rules/resources/DQC_US_0001/dqc_0001.json
> Update DQC1 configs.

- dqc_us_rules/_pkg_meta.py
- dqc_us_rules/dqc_us_0015.py
- Updated 0015 rule version to 1.1.1 to indicate a bugfix.
- Updated the _pkg_meta.py to update the version of the library.
> XS-3263: Update for 1.1.1 release

- dqc_us_rules/_pkg_meta.py
- Updated the pin to release 2.0.0RC14
> Update version to 2.0.0RC14

- dqc_us_rules/_pkg_meta.py
> Updated version to 2.0.0 RC 15

- dqc_us_rules/dqc_us_0013.py
- tests/unit_tests/test_dqc_us_0013.py
- Added a filter to the precondition sum to remove nulls
- Added a unit test to handle scenario
> XS-3290 DQC 13 occasionally throwing an error

- dqc_us_rules/_pkg_meta.py
> Updated tag to 2.0.0.RC16

- dqc_us_rules/_pkg_meta.py
> Updated tag to 2.0.0.RC17

- dqc_us_rules/_pkg_meta.py
- Changing the release candidate tag to 2.0.0.RC18
> Updated tag to 2.0.0.RC18

- dqc_us_rules/_pkg_meta.py
> Updated tag to 2.0.0.RC19

- dqc_us_rules/_pkg_meta.py
- dqc_us_rules/resources/DQC_US_0015/dqc_15_exclusion_rules.csv
- Removed space that was disallowing a member match
- Incremented release tag as the change is a bug fix and will necessitate a new release.
> XS-3312 Removed problematic space and incremented release

- dqc_us_rules/__init__.py
- Changed version number for the plugin
> XS-3677 Changed version number

- DQC_Testcases/DQC_0005/variation.xml
- dqc_us_rules/dqc_us_0005.py
- Added all currently possible S- form types including amendments.
> XS-3700 DQC 0005 Adding forms to exclusion list for 

- dqc_us_rules/_pkg_meta.py
- Updated version info in preparation for a new release.
> XS-3713 Update version info

- dqc_us_rules/_pkg_meta.py
> XS-3790 Incremented the release candidate number

- dqc_us_rules/_pkg_meta.py
> DQC update version info to 2.0.2

- README.md
- docs/README.md
- DOCUMENTATION CHANGES ONLY
- add language and links to root readme to clarify versioning of individual rules and releases
- update table on readme in docs to current versions
> update version table and readme versioning

- dqc_us_rules/_pkg_meta.py
- Changing version number for documentation change.
- Must be merged with https://github.com/DataQualityCommittee/dqc_us_rules/pull/218
Needs to be merged with PR https://github.com/DataQualityCommittee/dqc_us_rules/pull/218
> XS-3856 Increment version number for documentation change.

- .travis.yml
- requirements-dev.txt
- Changed unit test call
- Changed timeout for integration test
- Updated the requirements-dev.txt for new EFM plugin.]
> XS-4066 Updating integration tests and requirements-dev

- .travis.yml
- requirements-dev.txt
- Merging in master to pick up bug fix.
> Merging changes from master into next_q3_16 branch

- dqc_us_rules/_pkg_meta.py
- Incrementing version number.
> XS-4227 Incremented version number to allow repackaging

- .travis.yml
- dqc_us_rules/dqc_us_0001.py
- dqc_us_rules/resources/DQC_US_0001/dqc_0001.json
- dqc_us_rules/resources/DQC_US_0001/dqc_0001_2014.json
- dqc_us_rules/resources/DQC_US_0001/dqc_0001_2015.json
- dqc_us_rules/resources/DQC_US_0001/dqc_0001_2016.json
- Added InvestmentsNetAssetValueMember to FairValueByFairValueHierarchyLevelAxis
- Changed travis.yml to install regex
> XS-4544 Adding extension member to checked axes.

- dqc_us_rules/__init__.py
- dqc_us_rules/_pkg_meta.py
- Changed plugin version from 3.0 to 3.2.
> Changing plugin version number

- docs/README.md
- dqc_us_rules/_pkg_meta.py
- dqc_us_rules/dqc_us_0001.py
- dqc_us_rules/resources/DQC_US_0001/dqc_0001.json
- dqc_us_rules/resources/DQC_US_0001/dqc_0001_2014.json
- dqc_us_rules/resources/DQC_US_0001/dqc_0001_2015.json
- dqc_us_rules/resources/DQC_US_0001/dqc_0001_2016.json
- dqc_us_rules/resources/DQC_US_0001/dqc_0001_2017.json
- Added missing members
- Incremented version number
> XS-5059 Added missing members to ReinsurancePremiumsForInsuranceCompaniesByProductSegmentAxis

- dqc_us_rules/_pkg_meta.py
- Changed package version number to 3.4.0.
> Incrementing package version number

- .gitattributes
- dqc_us_rules/dqc_us_0008.py
- dqc_us_rules/resources/DQC_US_0001/dqc_0001.json
- dqc_us_rules/resources/DQC_US_0001/dqc_0001_2014.json
- dqc_us_rules/resources/DQC_US_0001/dqc_0001_2015.json
- dqc_us_rules/resources/DQC_US_0001/dqc_0001_2016.json
- dqc_us_rules/resources/DQC_US_0001/dqc_0001_2017.json
- DQC_0001 json edits
- DQC_0008 rule_key_index edit
> Update dqc_0001 jsons & dqc_us_0008 rule index key

- dqc_us_rules/__init__.py
- dqc_us_rules/_pkg_meta.py
- Changed package version number
> XS-5227 Changing package version numbers

- dqc_us_rules/_pkg_meta.py
- dqc_us_rules/dqc_us_0011.py
- Added two checks to verify structure before trying to evaluate.
- Incremented version number
> XS-5306 Fixing exceptions

- .github/PULL_REQUEST_TEMPLATE.md
- Removing Andrew from the checklist.
-
> Removing Andrew.

- dqc_us_rules/dqc_us_0008.py
- requirements-dev.txt
- requirements.txt
- Added the check to see if there are errors before trying to iterate through them
- Added openpyxl in the requirements as it's required.
> Fixes for Davids issues

- README.md
- xule/XuleFunctions.py
- Change XuleFunctions.py
- Change readme.md
> Update functions and readme files

- xule/rulesetMap.json
- Edited rulesetMap.json (for version 6.1.0)
> Update rulestMap.json for IFRS 2018

- plugin/validate/DQC.py
- plugin/xule/__init__.py
- re-establish functionality to view, update and merge custom .json files
> Fix rulesetmap management (desktop GUI) (#385)

- docs/DQC_US_0098/DQC_0098.md
- docs/DQC_US_0099/DQC_0099.md
- docs/DQC_US_0100/DQC_00100.md
- docs/README.md
- Add DQC_0098, DQC_0099 and DQC_100 Rule Submission forms for Committee review (v13)
- Update Rule Submission Form index
> Update rule submission forms for DQC review

- travis-run.sh
- Update dqc_0043 to handle add back of the loss on sale of disc ops.
- Update dqc_0145 for additional exceptions
- Increment version and recompile ruleset .zip files
- Update travis-run.sh to use XULE 23379.2 version (NB: version 20 is the last release for this version of XULE)
> Update v20.0.1 Approved
